//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.DatabaseConsistencyChecker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigurationItemResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationItemResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoenaSoft.DVDProfiler.DatabaseConsistencyChecker.ConfigurationItemResources", typeof(ConfigurationItemResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic: Combine profiles with AND.
        /// </summary>
        internal static string AndItem {
            get {
                return ResourceManager.GetString("AndItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count As: Must be equal to given number.
        /// </summary>
        internal static string CountAsEqualToItem {
            get {
                return ResourceManager.GetString("CountAsEqualToItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count As: Must not be equal to given number.
        /// </summary>
        internal static string CountAsNotEqualToItem {
            get {
                return ResourceManager.GetString("CountAsNotEqualToItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic: Exclude profiles.
        /// </summary>
        internal static string ExceptItem {
            get {
                return ResourceManager.GetString("ExceptItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast: Must (not) contain cast members.
        /// </summary>
        internal static string HasCastItem {
            get {
                return ResourceManager.GetString("HasCastItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew: Must (not) contain crew members.
        /// </summary>
        internal static string HasCrewItem {
            get {
                return ResourceManager.GetString("HasCrewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type: Custom Type must (not) be set.
        /// </summary>
        internal static string HasCustomMediaTypeItem {
            get {
                return ResourceManager.GetString("HasCustomMediaTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event: Must (not) contain event of the given type and user.
        /// </summary>
        internal static string HasEventItem {
            get {
                return ResourceManager.GetString("HasEventItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusion: Must (not) be excluded from online private listing.
        /// </summary>
        internal static string HasOnlinePrivateExclusionItem {
            get {
                return ResourceManager.GetString("HasOnlinePrivateExclusionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusion: Must (not) be excluded from online public listing.
        /// </summary>
        internal static string HasOnlinePublicExclusionItem {
            get {
                return ResourceManager.GetString("HasOnlinePublicExclusionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusion: Must (not) be excluded from DVD Profiler Mobile (PDA).
        /// </summary>
        internal static string HasPDAExclusionItem {
            get {
                return ResourceManager.GetString("HasPDAExclusionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusion: Must (not) be excluded from DVD Profiler for iPhone / Android.
        /// </summary>
        internal static string HasSmartPhoneExclusionItem {
            get {
                return ResourceManager.GetString("HasSmartPhoneExclusionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Number: Must (not) be set.
        /// </summary>
        internal static string IsCollectionNumberSetItem {
            get {
                return ResourceManager.GetString("IsCollectionNumberSetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Type: Must be part of given collection type.
        /// </summary>
        internal static string IsCollectionTypeItem {
            get {
                return ResourceManager.GetString("IsCollectionTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type: Custom Type must be equal to given custom media type.
        /// </summary>
        internal static string IsCustomMediaTypeItem {
            get {
                return ResourceManager.GetString("IsCustomMediaTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type: Must (not) be Blu-ray.
        /// </summary>
        internal static string IsMediaTypeBluRayItem {
            get {
                return ResourceManager.GetString("IsMediaTypeBluRayItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type: Must (not) be DVD.
        /// </summary>
        internal static string IsMediaTypeDVDItem {
            get {
                return ResourceManager.GetString("IsMediaTypeDVDItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type: Must (not) be HD-DVD.
        /// </summary>
        internal static string IsMediaTypeHDDVDItem {
            get {
                return ResourceManager.GetString("IsMediaTypeHDDVDItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type: Must (not) be Ultra-HD.
        /// </summary>
        internal static string IsMediaTypeUltraHDItem {
            get {
                return ResourceManager.GetString("IsMediaTypeUltraHDItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Type: Must not be part of given collection type.
        /// </summary>
        internal static string IsNotCollectionTypeItem {
            get {
                return ResourceManager.GetString("IsNotCollectionTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type: Custom Type must not be equal to given custom media type.
        /// </summary>
        internal static string IsNotCustomMediaTypeItem {
            get {
                return ResourceManager.GetString("IsNotCustomMediaTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Type: Must (not) be part of Owned collection.
        /// </summary>
        internal static string IsPartOfOwnedCollectionItem {
            get {
                return ResourceManager.GetString("IsPartOfOwnedCollectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Year: must (not) be set.
        /// </summary>
        internal static string IsProductionYearSet {
            get {
                return ResourceManager.GetString("IsProductionYearSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Time: must (not) be set.
        /// </summary>
        internal static string IsRunningTimeSetItem {
            get {
                return ResourceManager.GetString("IsRunningTimeSetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Origin: Must contain countries of origin.
        /// </summary>
        internal static string MustContainCountryOfOriginsItem {
            get {
                return ResourceManager.GetString("MustContainCountryOfOriginsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre: Must contain given genre.
        /// </summary>
        internal static string MustContainGenreItem {
            get {
                return ResourceManager.GetString("MustContainGenreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre: Must contain genres.
        /// </summary>
        internal static string MustContainGenresItem {
            get {
                return ResourceManager.GetString("MustContainGenresItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Company: Must contain media companies.
        /// </summary>
        internal static string MustContainMediaCompaniesItem {
            get {
                return ResourceManager.GetString("MustContainMediaCompaniesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio: Must contain studios.
        /// </summary>
        internal static string MustContainStudiosItem {
            get {
                return ResourceManager.GetString("MustContainStudiosItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag: Must contain given tag name.
        /// </summary>
        internal static string MustContainTagItem {
            get {
                return ResourceManager.GetString("MustContainTagItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Origin: Must not contain countries of origin.
        /// </summary>
        internal static string MustNotContainCountryOfOriginsItem {
            get {
                return ResourceManager.GetString("MustNotContainCountryOfOriginsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre: Must not contain given genre.
        /// </summary>
        internal static string MustNotContainGenreItem {
            get {
                return ResourceManager.GetString("MustNotContainGenreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre: Must not contain genres.
        /// </summary>
        internal static string MustNotContainGenresItem {
            get {
                return ResourceManager.GetString("MustNotContainGenresItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Company: Must not contain media companies.
        /// </summary>
        internal static string MustNotContainMediaCompaniesItem {
            get {
                return ResourceManager.GetString("MustNotContainMediaCompaniesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio: Must not contain studios.
        /// </summary>
        internal static string MustNotContainStudiosItem {
            get {
                return ResourceManager.GetString("MustNotContainStudiosItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag: Must not contain given tag name.
        /// </summary>
        internal static string MustNotContainTagItem {
            get {
                return ResourceManager.GetString("MustNotContainTagItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic: Combine profiles with OR.
        /// </summary>
        internal static string OrItem {
            get {
                return ResourceManager.GetString("OrItem", resourceCulture);
            }
        }
    }
}
