//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.DatabaseConsistencyChecker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigurationItemResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationItemResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoenaSoft.DVDProfiler.DatabaseConsistencyChecker.ConfigurationItemResources", typeof(ConfigurationItemResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic: Combine filters/checks with AND.
        /// </summary>
        internal static string AndItem {
            get {
                return ResourceManager.GetString("AndItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast: Birth Year must be larger / smaller than given value.
        /// </summary>
        internal static string CastMemberBirthYearIsLargerThanItem {
            get {
                return ResourceManager.GetString("CastMemberBirthYearIsLargerThanItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew: Birth Year must be larger / smaller than given value.
        /// </summary>
        internal static string CrewMemberBirthYearIsLargerThanItem {
            get {
                return ResourceManager.GetString("CrewMemberBirthYearIsLargerThanItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event: Must contain event with date larger / smaller than given value.
        /// </summary>
        internal static string EventDateDateIsLargerThanItem {
            get {
                return ResourceManager.GetString("EventDateDateIsLargerThanItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic: Exclude profiles.
        /// </summary>
        internal static string ExceptItem {
            get {
                return ResourceManager.GetString("ExceptItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Format: Aspect Ratio must be set.
        /// </summary>
        internal static string HasAspectRatioItem {
            get {
                return ResourceManager.GetString("HasAspectRatioItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review: Audio must be set.
        /// </summary>
        internal static string HasAudioReviewItem {
            get {
                return ResourceManager.GetString("HasAudioReviewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Track: Must contain given value.
        /// </summary>
        internal static string HasAudioTrackItem {
            get {
                return ResourceManager.GetString("HasAudioTrackItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Track: Must contain audio tracks.
        /// </summary>
        internal static string HasAudioTracksItem {
            get {
                return ResourceManager.GetString("HasAudioTracksItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box set: Must have child profiles.
        /// </summary>
        internal static string HasBoxSetChildrenItem {
            get {
                return ResourceManager.GetString("HasBoxSetChildrenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Type: Must be set.
        /// </summary>
        internal static string HasCaseTypeItem {
            get {
                return ResourceManager.GetString("HasCaseTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast: Must contain cast members.
        /// </summary>
        internal static string HasCastItem {
            get {
                return ResourceManager.GetString("HasCastItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Number: Must be set.
        /// </summary>
        internal static string HasCollectionNumberItem {
            get {
                return ResourceManager.GetString("HasCollectionNumberItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Format: Any Color Format must be checked.
        /// </summary>
        internal static string HasColorFormatItem {
            get {
                return ResourceManager.GetString("HasColorFormatItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Origin: Must contain countries of origin.
        /// </summary>
        internal static string HasCountryOfOriginsItem {
            get {
                return ResourceManager.GetString("HasCountryOfOriginsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew: Must contain crew members.
        /// </summary>
        internal static string HasCrewItem {
            get {
                return ResourceManager.GetString("HasCrewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type: Custom Type must be set.
        /// </summary>
        internal static string HasCustomMediaTypeItem {
            get {
                return ResourceManager.GetString("HasCustomMediaTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Format: Any Dimension must be checked.
        /// </summary>
        internal static string HasDimensionsItem {
            get {
                return ResourceManager.GetString("HasDimensionsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc: Must contain discs.
        /// </summary>
        internal static string HasDiscsItem {
            get {
                return ResourceManager.GetString("HasDiscsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review: DVD / Video must be set.
        /// </summary>
        internal static string HasDVDReviewItem {
            get {
                return ResourceManager.GetString("HasDVDReviewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easter Eggs: Must be set.
        /// </summary>
        internal static string HasEasterEggsItem {
            get {
                return ResourceManager.GetString("HasEasterEggsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event: Must contain event of the given event type and user.
        /// </summary>
        internal static string HasEventItem {
            get {
                return ResourceManager.GetString("HasEventItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review: Extras must be set.
        /// </summary>
        internal static string HasExtrasReviewItem {
            get {
                return ResourceManager.GetString("HasExtrasReviewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features: Must contain features.
        /// </summary>
        internal static string HasFeaturesItem {
            get {
                return ResourceManager.GetString("HasFeaturesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre: Must contain given value.
        /// </summary>
        internal static string HasGenreItem {
            get {
                return ResourceManager.GetString("HasGenreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre: Must contain genres.
        /// </summary>
        internal static string HasGenresItem {
            get {
                return ResourceManager.GetString("HasGenresItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Company: Must contain media companies.
        /// </summary>
        internal static string HasMediaCompaniesItem {
            get {
                return ResourceManager.GetString("HasMediaCompaniesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review: Movie must be set.
        /// </summary>
        internal static string HasMovieReviewItem {
            get {
                return ResourceManager.GetString("HasMovieReviewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusion: Must be excluded from online private listing.
        /// </summary>
        internal static string HasOnlinePrivateExclusionItem {
            get {
                return ResourceManager.GetString("HasOnlinePrivateExclusionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusion: Must be excluded from online public listing.
        /// </summary>
        internal static string HasOnlinePublicExclusionItem {
            get {
                return ResourceManager.GetString("HasOnlinePublicExclusionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview: Must be set.
        /// </summary>
        internal static string HasOverviewItem {
            get {
                return ResourceManager.GetString("HasOverviewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusion: Must be excluded from DVD Profiler Mobile (PDA).
        /// </summary>
        internal static string HasPDAExclusionItem {
            get {
                return ResourceManager.GetString("HasPDAExclusionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Year: Must be set.
        /// </summary>
        internal static string HasProductionYearItem {
            get {
                return ResourceManager.GetString("HasProductionYearItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase: Currency must be set.
        /// </summary>
        internal static string HasPurchaseCurrencyItem {
            get {
                return ResourceManager.GetString("HasPurchaseCurrencyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase: Date must be set.
        /// </summary>
        internal static string HasPurchaseDateItem {
            get {
                return ResourceManager.GetString("HasPurchaseDateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase: Place must be set.
        /// </summary>
        internal static string HasPurchasePlaceItem {
            get {
                return ResourceManager.GetString("HasPurchasePlaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase: Price must be set.
        /// </summary>
        internal static string HasPurchasePriceItem {
            get {
                return ResourceManager.GetString("HasPurchasePriceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating: Must be set.
        /// </summary>
        internal static string HasRatingItem {
            get {
                return ResourceManager.GetString("HasRatingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date: Must be set.
        /// </summary>
        internal static string HasReleaseDateItem {
            get {
                return ResourceManager.GetString("HasReleaseDateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Time: Must be set.
        /// </summary>
        internal static string HasRunningTimeItem {
            get {
                return ResourceManager.GetString("HasRunningTimeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusion: Must be excluded from DVD Profiler for iPhone / Android.
        /// </summary>
        internal static string HasSmartphoneExclusionItem {
            get {
                return ResourceManager.GetString("HasSmartphoneExclusionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRP: Currency must be set.
        /// </summary>
        internal static string HasSRPCurrencyItem {
            get {
                return ResourceManager.GetString("HasSRPCurrencyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRP: Price must be set.
        /// </summary>
        internal static string HasSRPPriceItem {
            get {
                return ResourceManager.GetString("HasSRPPriceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio: Must contain studios.
        /// </summary>
        internal static string HasStudiosItem {
            get {
                return ResourceManager.GetString("HasStudiosItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle: Must contain given value.
        /// </summary>
        internal static string HasSubtitleItem {
            get {
                return ResourceManager.GetString("HasSubtitleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle: Must contain subtitles.
        /// </summary>
        internal static string HasSubtitlesItem {
            get {
                return ResourceManager.GetString("HasSubtitlesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag: Must contain given value.
        /// </summary>
        internal static string HasTagItem {
            get {
                return ResourceManager.GetString("HasTagItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Format: Any Video Format must be checked.
        /// </summary>
        internal static string HasVideoFormatItem {
            get {
                return ResourceManager.GetString("HasVideoFormatItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Type: Must be equal to given value.
        /// </summary>
        internal static string IsCaseTypeItem {
            get {
                return ResourceManager.GetString("IsCaseTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Type: Must be part of given collection type value.
        /// </summary>
        internal static string IsCollectionTypeItem {
            get {
                return ResourceManager.GetString("IsCollectionTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count As: Must be equal to given value.
        /// </summary>
        internal static string IsCountAsItem {
            get {
                return ResourceManager.GetString("IsCountAsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type: Custom Type must be equal to given value.
        /// </summary>
        internal static string IsCustomMediaTypeItem {
            get {
                return ResourceManager.GetString("IsCustomMediaTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type: Must be Blu-ray.
        /// </summary>
        internal static string IsMediaTypeBluRayItem {
            get {
                return ResourceManager.GetString("IsMediaTypeBluRayItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type: Must be DVD.
        /// </summary>
        internal static string IsMediaTypeDVDItem {
            get {
                return ResourceManager.GetString("IsMediaTypeDVDItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type: Must be HD-DVD.
        /// </summary>
        internal static string IsMediaTypeHDDVDItem {
            get {
                return ResourceManager.GetString("IsMediaTypeHDDVDItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type: Must be Ultra-HD.
        /// </summary>
        internal static string IsMediaTypeUltraHDItem {
            get {
                return ResourceManager.GetString("IsMediaTypeUltraHDItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Type: Must be part of Owned collection.
        /// </summary>
        internal static string IsPartOfOwnedCollectionItem {
            get {
                return ResourceManager.GetString("IsPartOfOwnedCollectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase: Currency must be equal to given value.
        /// </summary>
        internal static string IsPurchaseCurrencyItem {
            get {
                return ResourceManager.GetString("IsPurchaseCurrencyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase: Place must be equal to given value.
        /// </summary>
        internal static string IsPurchasePlaceItem {
            get {
                return ResourceManager.GetString("IsPurchasePlaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating: Must be equal to given value.
        /// </summary>
        internal static string IsRatingItem {
            get {
                return ResourceManager.GetString("IsRatingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating: Rating System must be equal to given value.
        /// </summary>
        internal static string IsRatingSystemItem {
            get {
                return ResourceManager.GetString("IsRatingSystemItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRP: Currency must be equal to given value.
        /// </summary>
        internal static string IsSRPCurrencyItem {
            get {
                return ResourceManager.GetString("IsSRPCurrencyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic: Combine filters/checks with OR.
        /// </summary>
        internal static string OrItem {
            get {
                return ResourceManager.GetString("OrItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase: Date must be larger / smaller than given value.
        /// </summary>
        internal static string PurchaseDateIsLargerThanItem {
            get {
                return ResourceManager.GetString("PurchaseDateIsLargerThanItem", resourceCulture);
            }
        }
    }
}
