//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace DoenaSoft.DVDProfiler.DatabaseConsistencyChecker.Configuration_v1_1 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CheckConfiguration {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rule")]
        public RuleItem[] Rule;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Version;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RuleItem {
        
        /// <remarks/>
        public Item Filter;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Check")]
        public CheckItem[] Check;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasEventItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LogicItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AndItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExceptItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NoParamItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainCountryOfOriginsItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainCountryOfOriginsItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainMediaCompaniesItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainMediaCompaniesItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainStudiosItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainStudiosItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainGenresItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainGenresItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChoiceItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasPurchaseCurrencyItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasPurchasePriceItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasPurchasePlaceItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasPurchaseDateItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasBoxSetChildrenItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasDiscsItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasOverviewItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasSubtitlesItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasAudioTracksItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasFeaturesItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasVideoFormatItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasDimensionsItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasColorFormatItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasAspectRatioItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasRatingItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasReleaseDateItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChoiceStringItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsPurchasePlaceItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsPurchaseCurrencyItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasSubtitleItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasAudioTrackItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasRatingSystemEqualToItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasRatingEqualToItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BooleanValueItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasSmartPhoneExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasPDAExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasOnlinePrivateExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasOnlinePublicExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasCrewItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasCastItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsProductionYearSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsRunningTimeSetItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsCollectionNumberSetItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasCustomMediaTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeHDDVDItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeUltraHDItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeBluRayItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeDVDItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsPartOfOwnedCollectionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntValueItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountAsNotEqualToItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountAsEqualToItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringValueItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsNotCustomMediaTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsCustomMediaTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsNotCollectionTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsCollectionTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainTagItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainTagItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainGenreItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainGenreItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class Item {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckItem {
        
        /// <remarks/>
        public Item Item;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasEventItem : Item {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UserFirstName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UserLastName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public HasEventItemEventType EventType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum HasEventItemEventType {
        
        /// <remarks/>
        Watched,
        
        /// <remarks/>
        Returned,
        
        /// <remarks/>
        Borrowed,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AndItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExceptItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class LogicItem : Item {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AndItem : LogicItem {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("And")]
        public Item[] And;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrItem : LogicItem {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Or")]
        public Item[] Or;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExceptItem : LogicItem {
        
        /// <remarks/>
        public Item Except;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainCountryOfOriginsItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainCountryOfOriginsItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainMediaCompaniesItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainMediaCompaniesItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainStudiosItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainStudiosItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainGenresItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainGenresItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class NoParamItem : Item {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustNotContainCountryOfOriginsItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustContainCountryOfOriginsItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustNotContainMediaCompaniesItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustContainMediaCompaniesItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustNotContainStudiosItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustContainStudiosItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustNotContainGenresItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustContainGenresItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasPurchaseCurrencyItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasPurchasePriceItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasPurchasePlaceItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasPurchaseDateItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasBoxSetChildrenItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasDiscsItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasOverviewItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasSubtitlesItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasAudioTracksItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasFeaturesItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasVideoFormatItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasDimensionsItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasColorFormatItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasAspectRatioItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasRatingItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasReleaseDateItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChoiceStringItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsPurchasePlaceItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsPurchaseCurrencyItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasSubtitleItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasAudioTrackItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasRatingSystemEqualToItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasRatingEqualToItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class ChoiceItem : Item {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Choice;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasPurchaseCurrencyItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasPurchasePriceItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasPurchasePlaceItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasPurchaseDateItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasBoxSetChildrenItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasDiscsItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasOverviewItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasSubtitlesItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasAudioTracksItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasFeaturesItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasVideoFormatItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasDimensionsItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasColorFormatItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasAspectRatioItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasRatingItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasReleaseDateItem : ChoiceItem {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsPurchasePlaceItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsPurchaseCurrencyItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasSubtitleItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasAudioTrackItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasRatingSystemEqualToItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasRatingEqualToItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class ChoiceStringItem : ChoiceItem {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsPurchasePlaceItem : ChoiceStringItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsPurchaseCurrencyItem : ChoiceStringItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasSubtitleItem : ChoiceStringItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasAudioTrackItem : ChoiceStringItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasRatingSystemEqualToItem : ChoiceStringItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasRatingEqualToItem : ChoiceStringItem {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasSmartPhoneExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasPDAExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasOnlinePrivateExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasOnlinePublicExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasCrewItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasCastItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsProductionYearSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsRunningTimeSetItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsCollectionNumberSetItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasCustomMediaTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeHDDVDItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeUltraHDItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeBluRayItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeDVDItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsPartOfOwnedCollectionItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class BooleanValueItem : Item {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasSmartPhoneExclusionItem : BooleanValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasPDAExclusionItem : BooleanValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasOnlinePrivateExclusionItem : BooleanValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasOnlinePublicExclusionItem : BooleanValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasCrewItem : BooleanValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasCastItem : BooleanValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsProductionYearSet : BooleanValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsRunningTimeSetItem : BooleanValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsCollectionNumberSetItem : BooleanValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasCustomMediaTypeItem : BooleanValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsMediaTypeHDDVDItem : BooleanValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsMediaTypeUltraHDItem : BooleanValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsMediaTypeBluRayItem : BooleanValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsMediaTypeDVDItem : BooleanValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsPartOfOwnedCollectionItem : BooleanValueItem {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountAsNotEqualToItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountAsEqualToItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class IntValueItem : Item {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountAsNotEqualToItem : IntValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountAsEqualToItem : IntValueItem {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsNotCustomMediaTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsCustomMediaTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsNotCollectionTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsCollectionTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainTagItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainTagItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainGenreItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainGenreItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class StringValueItem : Item {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsNotCustomMediaTypeItem : StringValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsCustomMediaTypeItem : StringValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsNotCollectionTypeItem : StringValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsCollectionTypeItem : StringValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustNotContainTagItem : StringValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustContainTagItem : StringValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustNotContainGenreItem : StringValueItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustContainGenreItem : StringValueItem {
    }
}
