//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace DoenaSoft.DVDProfiler.DatabaseConsistencyChecker.Configuration_v1_0 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CheckConfiguration {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rule")]
        public RuleItem[] Rule;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Version;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VersionSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RuleItem {
        
        /// <remarks/>
        public Item Filter;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Check")]
        public CheckItem[] Check;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasEventItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LogicItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AndItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExceptItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NoParamItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainCountryOfOriginsItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainCountryOfOriginsItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainMediaCompaniesItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainMediaCompaniesItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainStudiosItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainStudiosItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainGenresItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainGenresItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BooleanItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasSmartPhoneExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasPDAExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasOnlinePrivateExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasOnlinePublicExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasCrewItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasCastItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsProductionYearSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsRunningTimeSetItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsCollectionNumberSetItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasCustomMediaTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeHDDVDItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeUltraHDItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeBluRayItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeDVDItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsPartOfOwnedCollectionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountAsNotEqualToItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountAsEqualToItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsNotCustomMediaTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsCustomMediaTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsNotCollectionTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsCollectionTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainTagItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainTagItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainGenreItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainGenreItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class Item {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckItem {
        
        /// <remarks/>
        public Item Item;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasEventItem : Item {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UserFirstName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UserLastName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public HasEventItemEventType EventType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum HasEventItemEventType {
        
        /// <remarks/>
        Watched,
        
        /// <remarks/>
        Returned,
        
        /// <remarks/>
        Borrowed,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AndItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExceptItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class LogicItem : Item {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AndItem : LogicItem {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("And")]
        public Item[] And;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrItem : LogicItem {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Or")]
        public Item[] Or;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExceptItem : LogicItem {
        
        /// <remarks/>
        public Item Except;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainCountryOfOriginsItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainCountryOfOriginsItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainMediaCompaniesItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainMediaCompaniesItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainStudiosItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainStudiosItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainGenresItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainGenresItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class NoParamItem : Item {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustNotContainCountryOfOriginsItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustContainCountryOfOriginsItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustNotContainMediaCompaniesItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustContainMediaCompaniesItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustNotContainStudiosItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustContainStudiosItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustNotContainGenresItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustContainGenresItem : NoParamItem {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasSmartPhoneExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasPDAExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasOnlinePrivateExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasOnlinePublicExclusionItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasCrewItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasCastItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsProductionYearSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsRunningTimeSetItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsCollectionNumberSetItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HasCustomMediaTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeHDDVDItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeUltraHDItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeBluRayItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsMediaTypeDVDItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsPartOfOwnedCollectionItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class BooleanItem : Item {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasSmartPhoneExclusionItem : BooleanItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasPDAExclusionItem : BooleanItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasOnlinePrivateExclusionItem : BooleanItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasOnlinePublicExclusionItem : BooleanItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasCrewItem : BooleanItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasCastItem : BooleanItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsProductionYearSet : BooleanItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsRunningTimeSetItem : BooleanItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsCollectionNumberSetItem : BooleanItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasCustomMediaTypeItem : BooleanItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsMediaTypeHDDVDItem : BooleanItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsMediaTypeUltraHDItem : BooleanItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsMediaTypeBluRayItem : BooleanItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsMediaTypeDVDItem : BooleanItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsPartOfOwnedCollectionItem : BooleanItem {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountAsNotEqualToItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountAsEqualToItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class IntItem : Item {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountAsNotEqualToItem : IntItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountAsEqualToItem : IntItem {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsNotCustomMediaTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsCustomMediaTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsNotCollectionTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsCollectionTypeItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainTagItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainTagItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustNotContainGenreItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MustContainGenreItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class StringItem : Item {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsNotCustomMediaTypeItem : StringItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsCustomMediaTypeItem : StringItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsNotCollectionTypeItem : StringItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsCollectionTypeItem : StringItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustNotContainTagItem : StringItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustContainTagItem : StringItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustNotContainGenreItem : StringItem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MustContainGenreItem : StringItem {
    }
}
